config/routes.rb
Rails.application.routes.draw do

  devise_for :users  
  resources :posts  
  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  get '/seminars', to: 'welcome#seminars'
  get '/weddings', to: 'welcome#weddings'
  get '/counseling', to: 'welcome#counseling'
  get '/book', to: 'welcome#book'
  get '/about', to: 'welcome#about'

 root 'welcome#index'

 get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,	 :validate => true
	attribute :email,	 :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,	 :validate => true
	attribute :nickname, :captcha => true #hidden field to protect from spam

	 def headers
		{
		  	:subject => "Contact Form",
		  	:to => "dawnaara@gmail.com",#change this to dad's email
		  	:from => %("#{name}" <#{email}>)
	  	}
	end
end

app/models/post.rb
class Post < ApplicationRecord

  has_attached_file :image, styles: { :medium => "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable - add back in when adding dad's email so he can sign up/in
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contacts = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = "Can not send message."
			render 'new'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
    #add will_paginate
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.order("created_at DESC").limit(4).offset(1)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Hooray, Charlie! Your blog post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index #change to home
  end

  def about
  end

  def counseling
  end

  def weddings
  end

  def seminars
  end

  def book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Thank you for your message.
              <small>I will get back to you as soon as I can.</small>
          </h1>
      </div>
  </div>

<div class="row content-wrapper lead">
      <div class="col-lg-12">
          <h1>In the meantime take good care of yourself, you deserve it!</h1>
      </div>
  </div>
</div>

app/views/contacts/new.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Do you have a question or comment?
              <small>Please send me a message.</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->
  <div class="row content-wrapper lead">

	<%= simple_form_for @contacts do |f| %>
		<%= f.input :name, placeholder: "Type your name here", required: true %>
	  	<%= f.input :email, placeholder: "Type your email here", required: true %>
	  	<%= f.input :message, placeholder: "Type your message here", as: :text, required: true %>
	  	<div class="hidden">
	  		<%= f.input :nickname, hint: 'leave this field blank' %>
	  	</div>
	  	<%= f.button :submit, 'Send Message', class: :simple_form_button %>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans+Condensed:300|Slabo+27px" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Latest compiled and minified CSS 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

	 <!-- for font awesome -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> 

</head>

<body>

<%= render 'shared/header' %>
<%= render 'shared/alerts' %>
<%= yield %>
<%= render 'shared/footer' %>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
var disqus_config = function () {
	this.page.url = '<%= request.original_url %> '; 
	this.page.identifier = '<%= @post.id %> ';
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//recipe-app.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<div class="container">

  <%= simple_form_for @post do |f| %>
    <%= f.error_notification %>

    <%= f.input :title, required: true, input_html: { class: 'form-control' } %>
    <%= f.input :body, required: true, input_html: { class: 'form-control' } %>
    <%= f.input :image, as: :file, input_html: { class: 'form-control' } %>
    <%= f.button :submit, class: "btn btn-primary" %>

  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Fix padding. should be 50px of padding to make sure the navbar doesn't overlap content!  -->
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Charlie's Thoughts
              <small>a.k.a words of wisdom</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->

  <div class="container">
    <div class="row">
      <% @posts.each do |post| %>

          <!-- Blog Entries Column -->
        <div class="col-md-5">
            <img class="img-responsive" <%= link_to (image_tag post.image.url(:medium)), post %>
            </img>
        </div>

        <!-- First Blog Post -->
        <div class="col-md-7">        
          <h2 class="title"><%= link_to post.title, post %></h2>
          <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>       
          <p class="lead"><%=h truncate(post.body, :length => 250, :separator => ' ') %></p>
          <p><%= link_to 'Read More', post %></p>
        </div>
    </div>
        <hr>
      <% end %>
  </div>
    
  <div class="row">
      <!-- will_paginate -->
    <div class="paginate text-center">  
      <%= will_paginate @posts %>
    </div>
  </div>

<!-- /.container -->

</div>

app/views/posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
    <!-- Fix padding. should be 50px of padding to make sure the navbar doesn't overlap content!  -->

<p id="notice"><%= notice %></p>

    <!-- Page Content -->
    <div class="container content-wrapper lead">

    <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-12">

                <!-- Title -->
                <h1 class="text-center"><%= @post.title %></h1>

                <!-- Date/Time -->
                <p class="date text-center"><%= time_ago_in_words(@post.created_at) %></p>

                <!-- Preview Image -->
                <!-- <img class="img-responsive center-block" src="http://placehold.it/900x300" alt=""> -->
				<img class="img-responsive center-block" <%= image_tag @post.image.url %></img>
                <hr>

                <!-- Post Content -->
                <p class="lead"><%= @post.body %></p>

                <% if user_signed_in? %>
                    <div id="admin_links">
                        <button type="submit" class="btn btn-default"><%= link_to "Edit", edit_post_path(@post) %></button>
                        <button type="submit" class="btn btn-default"><%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %></button>
                    </div>
                <% end %>

                <hr>                

                <!-- Blog Comments -->

			<button type="submit" class="btn btn-default"><%= link_to 'Back', posts_path %></button>
            </div>


        </div>
    <%= render 'disqus' %>
    </div>
        <!-- /.row -->

       

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline text-center">
                        <li>17315 Studebaker Road, Suite 130, Cerritos, CA 90703</li>
                    <li class="footer-menu-divider">&sdot;</li>
                        <li class="footer_links footer_links_mobile"><a href="tel:562-865-4075">(562) 865-4075</a></li>
                    <li class="footer-menu-divider">&sdot;</li>
                        <li class="footer_links"><a href="mailto:cara@sprintmail.com">cara@sprintmail.com</a></li>
                    <li class="footer-menu-divider">&sdot;</li>    
                    <li>&copy; 2016 Charles Ara</li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand bottom"><%= link_to 'FatherAra.com', root_path %></div>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav nav-pills navbar-nav navbar-right">
                <li>
                    <%= link_to 'BLOG', posts_path %>
                </li>
                <li>
                    <%= link_to 'ABOUT', about_path %>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SERVICES <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'COUNSELING', counseling_path %></li>
                    <li><%= link_to 'WEDDINGS', weddings_path %></li>
                    <li><%= link_to 'SEMINARS', seminars_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to 'BUY BOOK!', book_path %></a></li>
                  </ul>
                </li>

                <li>
                    <%= link_to 'CONTACT', new_contact_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/welcome/about.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Father Charles Ara, PhD
                <small>The Grass is Greener Where it's Watered</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Item Row -->
    <div class="row content-wrapper lead">
       <div class="col-lg-6">    
        <img class="img-responsive"
            <%= image_tag'super_gandi.jpg' %>
        </img>
        </div>
        <div class="col-lg-6">
        <p>From 1956 to 1970, he served as associate pastor in five large parishes in the Archdiocese of Los Angeles:  St. Lawrence Martyr in the South Bay area, St. Finbar's in the Burbank-Glendale area, Visitation in West Los Angeles, All Saints in El Sereno and St. Cecilia's in the Tustin-Santa Ana area of Orange County.</p>

        <p>On October 10, 1970 Father Ara added love and marriage to his priesthood. He and his wife, Shirley, have been blessed with five wonderful children.  Martin, Jose, Rana, Dawna and Matthew are all now young adults.</p>

        <p>Father Ara is available to preside over weddings for Catholics who for one reason or another are not being married at their parish church.  He also presides over non-denominational weddings and sometimes joins with a Jewish rabbi for an inter-faith ceremony.  In addition, Father Ara also conducts funerals and baptisms when requested.</p>

        <p>Father Ara is a licensed psychotherapist with a marriage counseling office in Cerritos, California.</p>

        <p>Father Ara can be reached at (562) 865-4075. His e-mail address is cara@sprintmail.com</p>        
    </div>
    </div>
    <!-- /.row -->
</div>

app/views/welcome/book.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">The Grass is Greener Where it's Watered
              <small>An inspiring book on marriage</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->

  <div class="row content-wrapper lead">
  	<div class="col-md-6">
        <img class="img-responsive" 
          	<%= image_tag 'grass_greener_book.jpg' %>
        </img>
    </div>
	<div class="col-md-6">
		<p>Father Ara's common sense book is a result of his 46 years of marriage counseling and the preparation of over 5,000 couples for their married lives together.</p> 

		<p><i>"You'll discover at leat 40 good reasons for having read Father Ara's book.   I discovered the Number One reason was:  It made me a better husband."</i> ~ Casey Kasem</p>

		<p>Learn over 100 ways to improve your marriage relationship.</p>

		<p>In "The Grass is Greener..."   you will learn:</p>
		
			<ul>
				<li>6 steps in creative problem solving designed especially for couples</li>
				<li>The 9 steps of a successful relationship</li>
				<li>10 steps to change fault finding in loving finding</li>
				<li>12 ways to raise your ATM (Attention To Mate) Quotient</li>
				<li>13 steps to conflict resolution</li>
				<li>14 ways to view your mate's faults in a positive light</li>
				<li>16 guidelines for positive communication with your lover</li>
				<li>16 reasons given by couples on why their marriages have lasted</li>
				<li>27 appealing behaviors that enhance relationships</li>
			</ul>

		<p>Father Ara's highly acclaimed book on successful relationships "The Grass Is Greener Where It's Watered" is available at bookstores everywhere. Father Ara is always positive!</p>

		<p>You can order Father Ara's book directly from him at a discounted price of $10, plus $3.00 shipping and handling. California residents, please add $0.85 state sales tax.</p>  
		Please send check or money order to: Shirley Ara, 11215 Park Street, Cerritos, CA  90703.</p>
	</div>
	</div>

	<div class="row content-wrapper text-center"><h2>Listen to the Book for Free</h2></div>
	<div class="row content-wrapper">
		<div class="col-md-5">
			<h2>Part 1: Chapters 1 - 4</h2>
			<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/115456477%3Fsecret_token%3Ds-TaKdx&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>	
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-5">
			<h2>Part 2: Chapters 5 - 10</h2>
			<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/115459475%3Fsecret_token%3Ds-g6xup&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
		</div>
	</div>
</div>

app/views/welcome/counseling.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Counseling
              <small>Marriage and Family Therapy</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->

  <div class="row content-wrapper">
  	
    <img class="img-responsive" 
      <%= image_tag 'counseling.jpg' %>
    </img>

    <hr>
  	  <p class ="lead">Does someone you know and care about need help in any of the situations described below? Perhaps you, yourself? If so, please call for an appointment or refer the person to me.</p>
      <h3>TEENAGER</h3>
      <p class="lead">On drugs? Run away from home? Doing poorly in school? School dropout? Discipline problem?<p>
 
      <h3>SPOUSE</h3>
      <p class="lead">Working too hard? Drinking too much? In love with someone else? 

      <h3>CHILD</h3>
      <p class="lead">Frequent temper tantrums? Slow learner?  Discipline problem? Low self esteem? Poor self image?</p>

      <h3>MARRIED</h3>
      <p class="lead">Lack of communication? Triangle love affair?  Financial problems? In-law problems? Sexual problems?</p>

      <h3>DIVORCED</h3>
        <p class="lead">Lonely? Fearful? Bitter? Angry? Guilty? Afraid to make a new beginning?</p>

      <h3>LIVING TOGETHER</h3>
      <p class="lead">Expectations not being met?  Misunderstandings? Undecided about getting married?</p>
      
      <h3>EMOTIONS</h3>
      <p class="lead">Suffering from anxiety? Depression? Anger? Guilt? Severe stress?</p>
      
      <h3>REMARRIED</h3>
      <p class="lead">Step-parenting problems? Custody problems? Stress in dealing with ex-spouse? Conflicts over visitation of the children?</p>
      
      <h3>OTHER</h3>
      <p class="lead">Unwanted pregnancy? Overweight? Alcohol or drug problem? Excessive smoking? Cancer patient in family? Elderly parents a burden? Loss of career? Death of a loved one?</p>

      <hr>
       	
		  <h3 class="text-center">LET ME HELP!</h3>
		  <p class ="lead text-center">CHARLES D. ARA, Ph.D.<br>17315 Studebaker Road, Suite 130, Cerritos, CA  90703<br>(562) 865-4075</p>

	</div>
</div>

app/views/welcome/index.html.erb
<!-- Header -->
<a name="about"></a>
<div class="intro-header"><div id="intro-header-overlay"></div>
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>FatherAra.com</h1> 
                    <hr class="intro-divider">
                    <h4>The Grass is Greener Where it's Watered</h4>

                    <!-- 
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                    -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->

<a  name="services"></a>
<div class="content-section-a">

    <div class="container blog-content-wrapper">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">The Grass is Greener Where it's Watered</h2>
                <p class="lead">Read my practical and inspiring book on marriage.</p>
                <p><%= link_to "Read More", book_path %></p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" <%= image_tag 'grass_is_greener_katherine_mccormack.jpg' %>
                </img>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-b">

    <div class="container blog-content-wrapper">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Use the Letter 'A' for Successful Relationships</h2>
                <p class="lead">Learn how affection, attention, acceptance, affirmation, appreciation, approval, awareness, appearl, adaptation, affable, and animation can help you be a better partner!</p>
                <p><%= link_to "Read More", book_path %></p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <img class="img-responsive"
                    <%= image_tag 'hands_drew_coffman.jpg' %>
                </img>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

    <div class="container blog-content-wrapper">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Be a LOVE finder, not a FAULT finder</h2>
                <p class="lead">In my 60 years of experience working with couples, I have found fault finding to be the #1 reason relationships break up.</p>
                <p><%= link_to "Read More", book_path %></p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive"
                    <%= image_tag 'happy-ben-rosett.jpg' %>
                </img>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

app/views/welcome/seminars.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Dr. Charles Ara
              <small>Seminars and Motivational Speaking</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->



<div class="row content-wrapper lead">
	<div class="col-md-6">
		<img class="img-responsive" 
	        <%= image_tag 'charlie_eating_icecream.jpg' %>
	    </img>
    </div>
    <div class="col-md-6">
		<p>Dr. Ara is a witty, experienced professional speaker.  He is also a popular guest on radio and television talk shows. His self-enrichment and communication seminars are humerous, informative, and uplifting. They are laced with good old common sense.  Charles Ara is on the teaching staffs of several community colleges.  He is a therapist in private practice with an office in Cerritos, CA.  He is a member of many professional organizations which include the California Association of Marriage and Family Therapists and the Professional Speakers' Network.</p>
		
		<h2>Keynote & Motivational Addresses</h2>

		<ul>
			<li>Developing Self-Esteem and Mental Fitness</li>
			<li>Farewell to Anger and Other Negative Emotions</li>
			<li>Thinking positively about Self and Life</li>
		</ul>
		<h2>Seminars</h2>
		<ul>
			<li>Resolving Conflicts in the School Environment</li>
			<li>Handling Stress - At Home, At Work, and in Life</li>
			<li>Managing Pressure and Tension at School</li>
			<li>Positive Communication in Negative Situations</li>
		</ul>
		
		<h2>Partial Client List</h2>
		<ul>	
			<li>Fullerton Joint Union High School District</li>		
			<li>Tustin Unified School District</li>
			<li>Anaheim City School District</li>		
			<li>Cerritos College Classified Staff</li>
			<li>Garvey Unified School District</li>		
			<li>Santa Ana Unified School District</li>
			<li>Teachers at Warren High in Downey Centralia School District</li>
		</ul>
		</div>

		<div class="col-md-12 clearfix">
		<h2>Testimonials</h2>

		<p><em>"You have a wonderful hands-on approach directly relating with the class's concerns and questions.  Your answers, woven with humor, were useful for a variety of situations.  Your wise common sense approach tore down walls people unintentionally build between each other."</em> ~ Kathleen R. Cooley, Anaheim school district</p>

		</p><em>"Many thanks for your time, effort and cooperation in helping to make Garvey's Health Fair a success."</em> ~ Caroline Van Winkle, Garvey school district</p>

		<p><em>"Since this was so important to everyone, I was delighted to have such a dynamic presenter covering the topic.  As you know, the comments on the session evaluations were extremely complimentary and enthusiastic.  I hope that we will have the pleasure of working with you in the future."</em> ~ Judy de Arakal, Tustin unified school district</p>

		<h2>For availability & scheduling please contact:</h2>

		<p>Charles D. Ara, Ph.D.

		17315 Studebaker Road, Suite 130, Cerritos, CA  90703   (562) 865-4075</p>
		</div>
	</div>
 
 </div>